name: FreeIPA CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_BUILD_IMAGE: registry.fedoraproject.org/fedora-toolbox:43
  DOCKER_BUILD_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/freeipa-builder
  IPA_TESTS_ENV_WORKING_DIR: /tmp/ipa_env
  IPA_TESTS_DOMAIN: ipa.test
  IPA_TESTS_REPO_PATH: /work
  IPA_TESTS_SCRIPTS: ipatests/azure/scripts
  IPA_PLATFORM: fedora

jobs:
  build-image:
    name: Build service image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_BUILD_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ipatests/buildimage/Dockerfile
          push: true
          tags: ${{ env.DOCKER_BUILD_REGISTRY }}/${{ github.repository_owner }}/ipa-ci-builder:pr-${{ github.event.pull_request.number }}
          build-args: |
            DOCKER_BUILD_IMAGE=${{ env.DOCKER_BUILD_IMAGE }}
          cache-from: type=registry,ref=${{ env.DOCKER_BUILD_REGISTRY }}/${{ github.repository_owner }}/ipa-ci-builder:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_BUILD_REGISTRY }}/${{ github.repository_owner }}/ipa-ci-builder:buildcache,mode=max
    outputs:
      image: ${{ env.DOCKER_BUILD_REGISTRY }}/${{ github.repository_owner }}/ipa-ci-builder:pr-${{ github.event.pull_request.number }}

  build-ipa:
    name: Build FreeIPA artifacts
    runs-on: ubuntu-latest
    needs: build-image
    container:
      image: ${{ needs.build-image.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: >-
        -v ./:/build
    defaults:
      run:
        working-directory: /build
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build freeipa packages
        run: |
            git config --global --add safe.directory /build

            echo "Running autoconf generator"
            ./autogen.sh  --enable-pylint --enable-rpmlint

            echo "Running make target 'rpms'"
            make V=0 rpms LOG_COMPILE='gdb.minimal -return-child-result -ex run -ex "thread apply all bt" -ex "quit" --args'

            mkdir -p dist/rpms_debuginfo
            find dist/rpms/ -type f \
                \( -name "*-debuginfo-*.rpm" -o -name '*-debugsource-*.rpm' \) \
                -exec mv {} dist/rpms_debuginfo/ \;

      - name: Upload FreeIPA rpms
        uses: actions/upload-artifact@v4
        with:
            name: freeipa-rpms
            path: ./dist/
